### PR TITLE
Restructure Protocol workflow for blocks without operations

### PR DESCRIPTION
**Pull request by gterzian**
Close https://github.com/massalabs/massa/issues/2747

### CODE REVIEW

File: massa-protocol-worker/src/protocol_worker.rs [hunk 1]
```diff
@@ -1127,6 +1143,23 @@ impl ProtocolWorker {
         }
 
         if !new_operations.is_empty() {
+            for (op_id, _) in received_ids.iter() {
+                if let Some(block_id) = self.awaiting_operations.get(op_id) {
+                    if let Some(info) = self.checked_headers.get_mut(block_id) {
+                        info.awaiting_operations.remove(op_id);
+                        if info.awaiting_operations.is_empty() {
+                            self.awaiting_operations.remove(op_id);
```
Comment (AurelienFT) [inline massa-protocol-worker/src/protocol_worker.rs:1151]: I don't understand why you remove the operation id only if the block has all his dependency filled. Because you inserted all operations of the block on this vector.

For example if your block have 10 operations and you received the first 9 you will not remove any from `self. awaiting_operations` and then remove only the 10th

**Comment by AurelienFT** [comment]
@gterzian I have added my changes but I don't really see how to link it. I think it's better if you are continuing on this as you seems to have a better idea of what we need to do then me.

File: massa-protocol-worker/src/protocol_worker.rs (hunk 1 above)
Comment (gterzian) [reply massa-protocol-worker/src/protocol_worker.rs:1150]: Ah yes that's an error, thanks for pointing it out.

**Comment by gterzian** [comment]
@AurelienFT Thanks for your help. As you can see from the latest commits, I will try to complete the workflow where we re-constitute the block from a header and a list of operations, and send it for processing to graph. 

It seems to be possible, although it does require doing things in protocol that could be encapsulated within `Wrapped`. Perhaps we can also adapt the wrapped API to better support what is going on in this PR. 

The "prototype" should be done by tomorrow...

File: massa-protocol-worker/src/protocol_worker.rs [hunk 2]
```diff
@@ -1239,25 +1296,52 @@ impl ProtocolWorker {
...
+                        }
+
+                        // Store entire operation list
+                        if let Some(info) = self.checked_headers.get_mut(&block_id) {
+                            info.operations = Some(operation_list.clone());
+                        } else {
+                            warn!("Missing block info for {}", block_id);
+                        }
+
+                        // Ask for the operations.
```
Comment (gterzian) [inline massa-protocol-worker/src/protocol_worker.rs:1336]: TODO: add dedicated workflow to ask for ops.

**Comment by gterzian** [comment]
@AurelienFT I could use some help with the serialization, see https://github.com/massalabs/massa/pull/2753/commits/1f5c6dec2776c8159547d6b7611017b34c1dcc1a

**Comment by gterzian** [comment]
TODOs:

- [ ] Update tests(see https://github.com/massalabs/massa/commit/1f5c6dec2776c8159547d6b7611017b34c1dcc1a)
- [ ] Network (de-) serialization

I think these can be done in parallel, so if anyone has time to help, let me know @massalabs/core-team

**Comment by gterzian** [comment]
@AurelienFT After rebasing I am getting the below error, would you have time to update your previous work with the operation ids?

```
error[E0015]: cannot call non-const fn `OperationIdsDeserializer::new` in constant functions
   --> massa-models/src/block.rs:236:34
    |
236 |             op_ids_deserializer: OperationIdsDeserializer::new(),
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: calls in constant functions are limited to constant functions, tuple structs and tuple variants
```

**Comment by gterzian** [comment]
> After rebasing I am getting the below error, would you have time to update your previous work with the operation ids?

@AurelienFT I think it's been solved by https://github.com/massalabs/massa/pull/2753/commits/033e6d3e0abf2f28153f18f3c0cdd20774484c08

**Comment by gterzian** [comment]
Still TODO:

- [ ] Investigate and fix apparent issue with block creation.
- [ ] Adapt protocol tests that have been ignored to the new messages.

File: massa-consensus-worker/src/consensus_worker.rs [hunk 3]
```diff
@@ -1279,12 +1257,11 @@ impl ConsensusWorker {
         for b_id in new_final_block_ids.into_iter() {
             if let Some(a_block) = self.block_db.get_active_block(&b_id) {
                 // List new final ops
-                new_final_ops.extend(
-                    a_block
-                        .operation_set
-                        .iter()
-                        .map(|(id, (_, exp))| (*id, (*exp, a_block.slot.thread))),
-                );
+                new_final_ops.extend(a_block.operation_set.iter().map(|(id, _)| {
```
Comment (AurelienFT) [inline massa-consensus-worker/src/consensus_worker.rs:1260]: We use this vector to pass it to notify the pool just above (L.1276) but the operations are already here if you can fetch them with the storage

File: massa-network-worker/src/messages.rs [hunk 4]
```diff
@@ -147,10 +150,22 @@ impl SerializeCompact for Message {
...
+                    };
+                    res.extend(u32::from(info_type).to_varint_bytes());
+                    if let AskForBlocksInfo::Operations(ids) = info {
+                        let op_ids_serializer = OperationIdsSerializer::new();
+                        op_ids_serializer.serialize(ids, &mut res)?;
+                    }
                 }
             }
+            Message::ReplyForBlocks(list) => {
+                panic!("Message::ReplyForBlocks should be constructed using shared storage.");
```
Comment (AurelienFT) [inline massa-network-worker/src/messages.rs:167]: You are using the old system of storage. With #2772 you will be able to pass storage to the serializer

File: massa-protocol-exports/src/protocol_controller.rs [hunk 5]
```diff
@@ -39,18 +43,16 @@ pub enum ProtocolEvent {
...
+#[derive(Debug)]
 pub enum ProtocolPoolEvent {
     /// Operations were received
     ReceivedOperations {
         /// the operations
         operations: Map<OperationId, WrappedOperation>,
-        /// whether or not to propagate operations
-        propagate: bool,
+        /// whether or not to signal the end of processing the batch.
+        done_signal: Option<oneshot::Sender<()>>,
```
Comment (AurelienFT) [inline massa-protocol-exports/src/protocol_controller.rs:55]: I don't understand why this change is made ?

**Comment by gterzian** [comment]
@AurelienFT Thanks for the review, I will look at your comments in more details.

In the meantime, could you please look at this failing test: `test_block_filling`. I'm wondering if it needs to be updated in light of the serialization changes(failure is on asserting the number of ops the block should contain based on the lenght of `serialized_data`).

**Comment by AurelienFT** [comment]
> @AurelienFT Thanks for the review, I will look at your comments in more details.
> 
> In the meantime, could you please look at this failing test: `test_block_filling`. I'm wondering if it needs to be updated in light of the serialization changes(failure is on asserting the number of ops the block should contain based on the lenght of `serialized_data`).

If you think it's a serialization problem why not merge both PR in the branch for the future and fix in this one ?

**Comment by AurelienFT** [comment]
@gterzian I have merged your PR with mine in #2862 . I have updated the serializer and deserializer to use the new format.
I let you continue working on the #2862 PR to fix warning and the failing test (I will give some help on this tomorrow morning) and address my comments that are here if you want. If you have any questions on the other PR do not hesitate to ask them and if everything is ok you can close this PR then.

File: massa-protocol-exports/src/protocol_controller.rs (hunk 5 above)
Comment (gterzian) [reply massa-protocol-exports/src/protocol_controller.rs:55]: To make protocol block on pool while it processes the operation, and adds to them storage, so that when protocol then re-creates the block and sends it to consensus, we are sure the operation are in storage. Could be removed perhaps with the latest changes to storage...

File: massa-consensus-worker/src/consensus_worker.rs (hunk 3 above)
Comment (gterzian) [reply massa-consensus-worker/src/consensus_worker.rs:1260]: Ok, thanks for the info, I'll look into it and will remove it if possible...

File: massa-network-worker/src/messages.rs (hunk 4 above)
Comment (gterzian) [reply massa-network-worker/src/messages.rs:167]: Ok, thanks for the info.

**Comment by gterzian** [comment]
@AurelienFT Ok thanks! I'll keep it open for now just for the various comments, and will continue on the other PR.

File: massa-consensus-worker/src/consensus_worker.rs (hunk 3 above)
Comment (gterzian) [reply massa-consensus-worker/src/consensus_worker.rs:1260]: I think the point is not to add the operations to storage, they are indeed already there, but rather to notify pool of them becoming final.

File: massa-network-worker/src/messages.rs (hunk 4 above)
Comment (gterzian) [reply massa-network-worker/src/messages.rs:167]: Can you perhaps make that change?

**Comment by gterzian** [comment]
Note: let's keep the branch for now...
